import type { AgentSkillCatalogEntry, SpaceMemoryConfig, VoiceStatus } from "@rakazo/contracts";
import type { GroupAvatarMember } from "@rakazo/ui-web";
import type { Dispatch, ReactNode, SetStateAction } from "react";
import type { NavigateFunction } from "react-router-dom";
import type { ArtifactTarget } from "../../lib/artifact-open";
import type { SettingsSection } from "../SettingsOverlay";
import type { Composer } from "./composer";
import type { Transcript } from "./transcript";
import type { Panel } from "./types";
import type { useComputer } from "./use-computer";
import type { useRoster } from "./use-roster";
import type { useRoutines } from "./use-routines";
import type { useSkills } from "./use-skills";
import type { useThreadSession } from "./use-thread-session";

export type ShellLayoutProps = ReturnType<typeof useRoster> &
  ReturnType<typeof useThreadSession> & {
    panel: Panel;
    setPanel: Dispatch<SetStateAction<Panel>>;
    activityMode: boolean;
    toggleActivityMode: () => void;
    usage: { inputTokens: number; outputTokens: number; runs: number } | null;
    setUsage: Dispatch<
      SetStateAction<{ inputTokens: number; outputTokens: number; runs: number } | null>
    >;
    userName: string;
    initials: string;
    sessionEmail: string | undefined;
    computerScreenError: ReactNode;
    navigate: NavigateFunction;
    groupId: string | undefined;
    pluginsOpen: boolean;
    setPluginsOpen: Dispatch<SetStateAction<boolean>>;
    settingsOpen: boolean;
    setSettingsOpen: Dispatch<SetStateAction<boolean>>;
    settingsSection: SettingsSection;
    setSettingsSection: Dispatch<SetStateAction<SettingsSection>>;
    messagingSettingsOpen: boolean;
    setMessagingSettingsOpen: Dispatch<SetStateAction<boolean>>;
    messagingSurfaceEnabled: boolean;
    messagingProviders: string[];
    memoryProviderConfig: SpaceMemoryConfig | null | undefined;
    setMemoryProviderConfig: Dispatch<SetStateAction<SpaceMemoryConfig | null | undefined>>;
    memoryProviderConfigRevision: { current: number };
    callOpen: boolean;
    setCallOpen: Dispatch<SetStateAction<boolean>>;
    voiceStatus: VoiceStatus | null;
    setVoiceStatus: Dispatch<SetStateAction<VoiceStatus | null>>;
    commandPaletteOpen: boolean;
    setCommandPaletteOpen: Dispatch<SetStateAction<boolean>>;
    peerConversation: { peerBotId: string; peerBotName: string } | null;
    setPeerConversation: Dispatch<
      SetStateAction<{ peerBotId: string; peerBotName: string } | null>
    >;
    openSettings: (section?: SettingsSection) => void;
    voiceStatusRefreshTimeout: () => Promise<never>;
    computer: ReturnType<typeof useComputer>["computer"];
    computerOpen: boolean;
    setComputerOpen: Dispatch<SetStateAction<boolean>>;
    computerViewport: { height: number; offsetTop: number } | null;
    booting: boolean;
    embeddedScreenUrl: string | null;
    openComputer: () => void | Promise<void>;
    releaseComputer: ReturnType<typeof useComputer>["releaseComputer"];
    refreshComputerScreen: (id: string) => Promise<unknown>;
    hasControl: boolean;
    setRoutineDraft: ReturnType<typeof useRoutines>["setRoutineDraft"];
    setRoutineWebhookSecret: ReturnType<typeof useRoutines>["setRoutineWebhookSecret"];
    setEditingRoutine: ReturnType<typeof useRoutines>["setEditingRoutine"];
    setRoutineError: ReturnType<typeof useRoutines>["setRoutineError"];
    activeRoutines: ReturnType<typeof useRoutines>["routines"];
    routineDraft: ReturnType<typeof useRoutines>["routineDraft"];
    editingRoutine: ReturnType<typeof useRoutines>["editingRoutine"];
    routineWebhookSecret: ReturnType<typeof useRoutines>["routineWebhookSecret"];
    savingRoutine: boolean;
    runningRoutine: boolean;
    routineError: string | null;
    ensureWebhookSecret: ReturnType<typeof useRoutines>["ensureWebhookSecret"];
    saveRoutine: ReturnType<typeof useRoutines>["saveRoutine"];
    testRunRoutine: ReturnType<typeof useRoutines>["testRunRoutine"];
    setDeleteRoutineTarget: ReturnType<typeof useRoutines>["setDeleteRoutineTarget"];
    deleteRoutineTarget: ReturnType<typeof useRoutines>["deleteRoutineTarget"];
    agentSkills: AgentSkillCatalogEntry[];
    setAgentSkills: Dispatch<SetStateAction<AgentSkillCatalogEntry[]>>;
    refreshAgentSkills: () => void;
    teachBusy: boolean;
    recordingSkill: ReturnType<typeof useSkills>["taughtSkills"][number] | null;
    needsComputer: boolean;
    composerRunning: boolean;
    transcriptRunning: boolean;
    takeoverReason: string | undefined;
    dockedAsk: Parameters<typeof Composer>[0]["dockedAsk"];
    dockedAskMessage: import("@rakazo/contracts").ThreadMessage | undefined;
    displayedRunError: string | null;
    displayedRunErrorId: string | null;
    handleRunErrorPresented: (runId: string) => void;
    dismissComposerError: () => void;
    transcriptMessages: import("@rakazo/contracts").ThreadMessage[];
    transcriptArtifactTarget: ArtifactTarget;
    workingBots: GroupAvatarMember[];
    answerableAskMessageId: string | null;
    resolveTranscriptMemberName: (botId: string | undefined) => string | undefined;
    resolveTranscriptBot: Parameters<typeof Transcript>[0]["peerBot"];
    replyTargetName: string | undefined;
    composerMentionTargets: Parameters<typeof Composer>[0]["mentionTargets"];
  };
